import React, { useMemo, useState } from 'react';
import { api } from '../api.js';
import { formatAmount, shortAddress, unique } from '../utils.js';
import { Badge, Button, EmptyState, MetricCard, Panel, SectionHeader } from './Primitives.jsx';

const tone = (index) => ['#2e6da4','#8a4f98','#b36b24','#2c7b61','#b34343'][index % 5];
const grouped = transactions => Object.entries((transactions || []).reduce((result, tx) => { const day = String(tx.timestamp || 'Unknown').slice(0, 10); result[day] = (result[day] || 0) + 1; return result; }, {})).slice(-12);

function BarChart({ title, data, onClick, suffix = '' }) {
  const max = Math.max(1, ...data.map(item => Number(item.value) || 0));
  return <Panel className="analytics-chart"><SectionHeader eyebrow="Observed activity" title={title}/><div className="bar-chart">{data.length ? data.map((item, index) => <button key={item.label} onClick={() => onClick?.(item)} title={`${item.label}: ${item.value}${suffix}`}><i style={{ height: `${Math.max(6, (Number(item.value) || 0) / max * 100)}%`, background: tone(index) }}/><strong>{item.value}{suffix}</strong><span>{item.label}</span></button>) : <EmptyState title="No chartable evidence" description="This case does not contain the evidence needed for this view."/>}</div></Panel>;
}

export function VisualAnalytics({ investigation, onTab }) {
  const activity = useMemo(() => grouped(investigation.transactions).map(([label, value]) => ({ label: label.slice(5), value })), [investigation]);
  const risk = (investigation.risk?.breakdown || []).map(item => ({ label: item.type.replaceAll('_', ' '), value: item.points || 0 }));
  const hops = Object.entries((investigation.paths || []).reduce((result, path) => { const key = `Hop ${path.hop || 1}`; result[key] = (result[key] || 0) + 1; return result; }, {})).map(([label, value]) => ({ label, value }));
  const roles = (investigation.network_analytics?.candidates || []).reduce((result, item) => { const key = String(item.role || 'other').replaceAll('_', ' '); result[key] = (result[key] || 0) + 1; return result; }, {});
  return <div className="analytics-workspace"><SectionHeader eyebrow="Visual analytics" title="Evidence-derived activity and network structure" description="All charts are calculated from the current stored blockchain evidence. Click a chart to continue the corresponding investigation workflow."/><div className="metric-grid four"><MetricCard label="Observed transfers" value={investigation.transactions?.length || 0} tone="blue"/><MetricCard label="Traced paths" value={investigation.paths?.length || 0} tone="purple"/><MetricCard label="Risk rules" value={risk.length} tone="amber"/><MetricCard label="Topology candidates" value={investigation.network_analytics?.candidates?.length || 0} tone="teal"/></div><div className="analytics-grid"><BarChart title="Transaction activity over time" data={activity} onClick={() => onTab('transactions')}/><BarChart title="Risk indicator contribution" data={risk} onClick={() => onTab('risk')} suffix=" pts"/><BarChart title="Fund-flow hop distribution" data={hops} onClick={() => onTab('fund-flow')}/><BarChart title="Network role distribution" data={Object.entries(roles).map(([label, value]) => ({ label, value }))} onClick={() => onTab('topology')}/></div></div>;
}

export function PatternIntelligence({ investigation, onTab, onCapture }) {
  const indicators = investigation.suspicious_activity?.indicators || [];
  const topology = investigation.network_analytics?.candidates || [];
  const patterns = [
    ...indicators.map(item => ({ name: item.message, type: 'Behavioral rule indicator', severity: item.severity || 'MEDIUM', evidence: item.supporting_transactions || [], source: item.source || 'tracex_rules', action: 'transactions', raw: item })),
    ...topology.map(item => ({ name: String(item.role || 'Network role').replaceAll('_', ' '), type: 'Topology analysis role', severity: 'MEDIUM', evidence: [item.address], source: 'network_analytics', action: 'fund-flow', raw: item }))
  ];
  return <div className="stack"><SectionHeader eyebrow="Automatic pattern recognition" title="Behavioral patterns from observed case evidence" description="TraceX evaluates transparent behavioral and network connectivity rules, not subjective conclusions."/>{patterns.length ? <div className="pattern-grid">{patterns.map((pattern, index) => <Panel key={`${pattern.name}-${index}`} className="pattern-card"><Badge tone={String(pattern.severity).toLowerCase()==='high'?'danger':'warning'}>{pattern.severity}</Badge><h3>{pattern.name}</h3><p>{pattern.type}</p><dl><div><dt>Detector</dt><dd>{pattern.source}</dd></div><div><dt>Supporting references</dt><dd>{pattern.evidence.length || 'Available in case evidence'}</dd></div><div><dt>Rule version</dt><dd>TraceX rules v1</dd></div></dl><div className="inline-actions"><Button variant="secondary" onClick={() => onTab(pattern.action)}>View supporting evidence</Button>{onCapture && <Button variant="ghost" onClick={() => onCapture({ evidence_type: 'RISK_INDICATOR', title: `Pattern: ${pattern.name}`, source_provider: 'TraceX rule analysis', snapshot: { type: pattern.raw.type || pattern.raw.role, source: pattern.source, message: pattern.name, severity: pattern.severity, points: pattern.raw.points } })}>Capture</Button>}</div></Panel>)}</div> : <EmptyState title="No pattern triggered" description="The current case did not meet any configured behavioral or topology pattern rule."/>}</div>;
}

export function PotentialMovement({ investigation }) {
  const paths = investigation.paths || [], latest = paths.at(-1), indicators = investigation.suspicious_activity?.indicators || [];
  const hasSplit = indicators.some(item => item.type === 'fund_splitting'), hasRapid = indicators.some(item => item.type === 'rapid_movement');
  const scenarios = [hasSplit && ['Split / fan-out scenario','Observed splitting behavior','A new outgoing transfer to multiple distinct counterparties within the monitoring window.'], hasRapid && ['Rapid forwarding scenario','Observed rapid-movement rule match','A new outgoing transfer shortly after an incoming transfer.'], investigation.exchange_attributions?.length && ['Potential entity interaction','Observed entity/VASP attribution in the current trace','A new transfer to an address matching the same attribution dataset.']].filter(Boolean);
  return <div className="stack"><SectionHeader eyebrow="Hypothetical analysis" title="Potential next-movement analysis" description="These are hypothetical analytical scenarios, not observed blockchain transactions and not predictions of a specific future wallet."/><Panel className="scenario-observed"><span className="eyebrow">Observed blockchain state</span>{latest ? <div className="observed-route"><strong>{shortAddress(latest.from)}</strong><i>→</i><strong>{shortAddress(latest.to)}</strong><small>{formatAmount(latest.amount)} {latest.asset} · {latest.timestamp}</small></div> : <EmptyState title="No traced path available" description="TraceX needs an observed path before it can describe a structural scenario."/>}</Panel><div className="scenario-boundary">HYPOTHETICAL ANALYTICAL SCENARIOS</div><div className="scenario-grid">{scenarios.length ? scenarios.map(([title, basis, confirmation], index) => <Panel key={title} className="scenario-card"><span>SCENARIO {String(index + 1).padStart(2, '0')}</span><h3>{title}</h3><dl><div><dt>Structural basis</dt><dd>{basis}</dd></div><div><dt>Supporting observed pattern</dt><dd>{indicators.map(item => item.message).slice(0, 2).join('; ') || 'Observed fund-flow structure'}</dd></div><div><dt>What would support this scenario</dt><dd>{confirmation}</dd></div><div><dt>Monitoring relevance</dt><dd>Monitor the current case wallet for the confirmation condition.</dd></div></dl><div className="scenario-flow"><b>OBSERVED WALLET</b><i>⇢</i><b>{title.includes('entity') ? 'POTENTIAL VASP' : 'POTENTIAL INTERMEDIARY'}</b></div></Panel>) : <EmptyState title="No scenario basis detected" description="TraceX will not create a hypothetical scenario without a supporting observed pattern."/>}</div></div>;
}

export function ApiExplorer({ investigation }) {
  const [endpoint, setEndpoint] = useState('case'), [result, setResult] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const execute = async () => { if (!investigation && endpoint !== 'config' && endpoint !== 'openapi') return; setBusy(true); setError(''); const started = performance.now(); try { const response = endpoint === 'case' ? await api.case(investigation.investigation_id) : endpoint === 'network' ? await api.network(investigation.investigation_id) : endpoint === 'config' ? await api.config() : endpoint === 'openapi' ? await fetch('/api/docs/openapi.json').then(r => r.json()) : await api.workspace(investigation.investigation_id); setResult({ data: response, latency: Math.round(performance.now() - started) }); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const catalog = { case: `GET /api/history/${investigation?.investigation_id || ':caseId'}`, network: `GET /api/fraud-network/${investigation?.investigation_id || ':caseId'}`, workspace: `GET /api/cases/${investigation?.investigation_id || ':caseId'}/workspace`, config: 'GET /api/config', openapi: 'GET /api/docs/openapi.json' };
  return <div className="developer-platform"><SectionHeader eyebrow="TraceX API" title="Blockchain investigation intelligence as an API" description="Execute real local TraceX endpoints. The response below is the same backend intelligence consumed by the application."/><Panel className="api-console"><div><label>Endpoint<select value={endpoint} onChange={e => setEndpoint(e.target.value)}>{Object.entries(catalog).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></label><pre>{`curl ${window.location.origin}${catalog[endpoint]}`}</pre><Button onClick={execute} disabled={busy}>{busy ? 'Executing…' : 'Execute request'}</Button></div><div className="api-response"><header><Badge tone={result?'success':'neutral'}>{result?'200 OK':'READY'}</Badge>{result && <small>{result.latency} ms · local TraceX backend</small>}</header>{error ? <p className="error-copy">{error}</p> : result ? <><pre>{JSON.stringify(result.data, null, 2).slice(0, 9000)}</pre><Button variant="secondary" onClick={() => window.navigator.clipboard?.writeText(JSON.stringify(result.data, null, 2))}>Copy JSON</Button></> : <p>Execute an endpoint to inspect actual JSON, status, latency, and provenance.</p>}</div></Panel></div>;
}
