import React, { useMemo, useState } from 'react';
import { Badge, Button, CopyValue, EmptyState, Panel, SectionHeader } from './Primitives.jsx';
import { formatDate } from '../utils.js';

const evidenceTypes=['TRANSACTION','WALLET','TRACED_PATH','RISK_INDICATOR','VASP_ATTRIBUTION','EXTERNAL_INTELLIGENCE','RELATED_CASE_RELATIONSHIP','NETWORK_NODE','BRIDGE_INTERACTION','ALERT','TIMELINE_EVENT','REPORT_SNAPSHOT'];

export function CaseInspector({ workspace, onUpdate, onToast }) {
  const item=workspace?.case; const [editing,setEditing]=useState(false); const [form,setForm]=useState({});
  if(!item)return null;
  const open=()=>{setForm({case_title:item.case_title||'',case_summary:item.case_summary||'',assigned_investigator:item.assigned_investigator||'',priority:item.priority||'MEDIUM',tags:(item.tags||[]).join(', '),case_status:item.case_status||'NEW'});setEditing(true);};
  const save=async()=>{try{await onUpdate({...form,tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean)});setEditing(false);onToast('Case details updated.');}catch(error){onToast(error.message,'error');}};
  return <Panel className="case-management"><SectionHeader eyebrow="Case management" title={item.case_title} description={`${item.case_reference} · Last updated ${formatDate(item.updated_at)}`} action={<Button variant="secondary" onClick={open}>Edit case</Button>}/><div className="case-management-grid"><div><span>Status</span><Badge tone={item.case_status==='CLOSED'?'neutral':'blue'}>{item.case_status.replaceAll('_',' ')}</Badge></div><div><span>Priority</span><Badge tone={item.priority==='CRITICAL'?'red':item.priority==='HIGH'?'amber':'neutral'}>{item.priority}</Badge></div><div><span>Assigned investigator</span><strong>{item.assigned_investigator||'Unassigned'}</strong></div><div><span>Tags</span><strong>{(item.tags||[]).join(', ')||'None'}</strong></div></div>{editing&&<div className="case-editor"><label>Case title<input value={form.case_title} onChange={e=>setForm({...form,case_title:e.target.value})}/></label><label>Summary<textarea value={form.case_summary} onChange={e=>setForm({...form,case_summary:e.target.value})}/></label><div className="form-grid"><label>Investigator<input value={form.assigned_investigator} onChange={e=>setForm({...form,assigned_investigator:e.target.value})}/></label><label>Tags (comma-separated)<input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['LOW','MEDIUM','HIGH','CRITICAL'].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={form.case_status} onChange={e=>setForm({...form,case_status:e.target.value})}>{['NEW','ACTIVE','UNDER_REVIEW','ESCALATED','CLOSED'].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="inline-actions"><Button onClick={save}>Save case</Button><Button variant="secondary" onClick={()=>setEditing(false)}>Cancel</Button></div></div>}</Panel>;
}

export function EvidenceWorkspace({ workspace, onVerify, onAddNote, onAddFinding, onCapture, onToast }) {
  const [filter,setFilter]=useState(''),[type,setType]=useState('ALL'),[note,setNote]=useState(''),[finding,setFinding]=useState({title:'',description:'',evidence_ids:''});
  const evidence=useMemo(()=> (workspace?.evidence||[]).filter(item=>(type==='ALL'||item.evidence_type===type)&&`${item.evidence_id} ${item.title} ${item.transaction_hash||''} ${item.wallet_address||''}`.toLowerCase().includes(filter.toLowerCase())),[workspace,filter,type]);
  const verify=async id=>{try{const result=await onVerify(id);onToast(result.verified?'Evidence integrity verified.':'Evidence integrity mismatch detected.',result.verified?'success':'error');}catch(error){onToast(error.message,'error');}};
  const saveNote=async()=>{if(!note.trim())return;try{await onAddNote({note_type:'GENERAL_CASE_NOTE',content:note});setNote('');onToast('Investigator note saved.');}catch(error){onToast(error.message,'error');}};
  const saveFinding=async()=>{if(!finding.title.trim()||!finding.description.trim())return;try{await onAddFinding({...finding,evidence_ids:finding.evidence_ids.split(',').map(x=>x.trim()).filter(Boolean)});setFinding({title:'',description:'',evidence_ids:''});onToast('Finding recorded as investigator-authored material.');}catch(error){onToast(error.message,'error');}};
  return <div className="stack"><Panel><SectionHeader eyebrow="Evidence center" title="Retained evidence" description="Captured snapshots are immutable; SHA-256 verification proves the stored snapshot has not changed." action={<Button onClick={()=>onCapture({evidence_type:'REPORT_SNAPSHOT',title:'Investigation report snapshot',source_type:'investigator_workspace'})}>Capture evidence</Button>}/><div className="evidence-filters"><input placeholder="Search evidence ID, title, wallet, hash" value={filter} onChange={e=>setFilter(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value)}><option>ALL</option>{evidenceTypes.map(x=><option key={x}>{x}</option>)}</select></div>{evidence.length?<div className="evidence-list">{evidence.map(item=><article key={item.evidence_id}><div><Badge tone="purple">{item.evidence_type.replaceAll('_',' ')}</Badge><strong>{item.title}</strong><small>{item.evidence_id} · {formatDate(item.captured_at)}</small>{item.transaction_hash&&<CopyValue value={item.transaction_hash}/>}</div><div><Badge tone="success">SHA-256</Badge><Button variant="secondary" onClick={()=>verify(item.evidence_id)}>Verify</Button></div></article>)}</div>:<EmptyState title="No retained evidence yet" description="Capture a transaction, wallet, path, alert, or report snapshot from the investigation."/>}</Panel><Panel><SectionHeader eyebrow="Investigator workspace" title="Notes and findings" description="Notes are leads. Findings should cite retained evidence IDs."/><div className="form-grid"><label>New note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Record an investigative observation…"/></label><div className="align-end"><Button onClick={saveNote}>Save note</Button></div></div><div className="finding-form"><label>Finding title<input value={finding.title} onChange={e=>setFinding({...finding,title:e.target.value})}/></label><label>Evidence IDs<input value={finding.evidence_ids} onChange={e=>setFinding({...finding,evidence_ids:e.target.value})} placeholder="EV-0001, EV-0002"/></label><label>Finding description<textarea value={finding.description} onChange={e=>setFinding({...finding,description:e.target.value})}/></label><Button onClick={saveFinding}>Create finding</Button></div><div className="workspace-records">{(workspace?.findings||[]).map(item=><article key={item.finding_id}><Badge tone="amber">{item.classification}</Badge><strong>{item.finding_id} · {item.title}</strong><p>{item.description}</p><small>Evidence: {(item.evidence_ids||[]).join(', ')||'none cited'}</small></article>)}{(workspace?.notes||[]).slice(0,8).map(item=><article key={item.note_id}><Badge>{item.note_type}</Badge><strong>{item.note_id}</strong><p>{item.content}</p></article>)}</div></Panel></div>;
}

export function EvidenceCapture({ draft, onSave, onClose }) {
  const [form,setForm]=useState({evidence_type:draft?.evidence_type||'TRANSACTION',title:draft?.title||'',wallet_address:draft?.wallet_address||'',transaction_hash:draft?.transaction_hash||'',source_type:draft?.source_type||'investigator_workspace',source_provider:draft?.source_provider||'TraceX',investigator_label:'',investigator_note:''});
  if(!draft)return null;
  return <div className="drawer-backdrop"><aside className="drawer"><header><div><span className="eyebrow">Evidence capture</span><h2>Save bounded snapshot</h2><p>Only the supplied case data is retained and integrity-hashed.</p></div></header><div className="drawer-content"><label>Type<select value={form.evidence_type} onChange={e=>setForm({...form,evidence_type:e.target.value})}>{evidenceTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Wallet address<input value={form.wallet_address} onChange={e=>setForm({...form,wallet_address:e.target.value})}/></label><label>Transaction hash<input value={form.transaction_hash} onChange={e=>setForm({...form,transaction_hash:e.target.value})}/></label><label>Investigator label<input value={form.investigator_label} onChange={e=>setForm({...form,investigator_label:e.target.value})}/></label><label>Note<textarea value={form.investigator_note} onChange={e=>setForm({...form,investigator_note:e.target.value})}/></label><div className="inline-actions"><Button onClick={()=>onSave(form)}>Capture and hash</Button><Button variant="secondary" onClick={onClose}>Cancel</Button></div></div></aside></div>;
}
