import React, { useState } from 'react';
import { navigate } from '../components/AppShell.jsx';

const nodes=[
  ['victim','Victim wallet','0x71C...A92','12 transactions','2.4 ETH','Low'],
  ['suspect','Suspect wallet','0x9D3...E71','8 transactions','2.4 ETH','High'],
  ['middle-a','Intermediary','0xB1A...198','4 transactions','0.9 ETH','Medium'],
  ['middle-b','Intermediary','0xC84...B21','5 transactions','0.8 ETH','Medium'],
  ['middle-c','Intermediary','0xA77...1D3','3 transactions','0.7 ETH','Medium'],
  ['exchange','Potential VASP endpoint','Exchange cluster','18 transactions','2.4 ETH','Review']
];

function NetworkDiagram({story=false}){
  const [hover,setHover]=useState(null);
  const activePath=hover==='exchange';
  return <div className={`landing-network ${story?'story-network':''}`}>
    <svg viewBox="0 0 760 400" aria-label="Simulated blockchain fund flow">
      <defs><filter id="soft"><feGaussianBlur stdDeviation="3"/></filter></defs>
      {[[120,68,280,116],[280,116,430,190],[430,190,260,293],[430,190,430,293],[430,190,600,293],[260,293,430,350],[430,293,430,350],[600,293,430,350]].map(([x1,y1,x2,y2],i)=><g key={i} className={activePath?'network-path active':'network-path'}><line x1={x1} y1={y1} x2={x2} y2={y2}/><circle r="3"><animateMotion dur={`${3+i*.28}s`} repeatCount="indefinite" path={`M${x1},${y1} L${x2},${y2}`}/></circle></g>)}
      {nodes.map(([id,label,address,count,amount,risk],i)=>{const xy=[[120,68],[280,116],[260,293],[430,293],[600,293],[430,350]][i];return <g key={id} transform={`translate(${xy[0]} ${xy[1]})`} className={`landing-node ${id} ${hover===id||activePath&&id!=='victim'?'active':''}`} onMouseEnter={()=>setHover(id)} onMouseLeave={()=>setHover(null)}><circle r={id==='exchange'?28:22}/><circle className="node-core" r={id==='exchange'?9:6}/><text y="-35">{label}</text><text className="address" y="43">{address}</text>{hover===id&&<foreignObject x="-72" y="-105" width="144" height="55"><div className="network-tooltip"><b>{count}</b><span>{amount} · {risk} risk</span></div></foreignObject>}</g>})}
    </svg>
    <div className="network-caption"><span><i/> Simulated live fund flow</span><span>Hover an entity to inspect</span></div>
  </div>;
}

export default function LandingPage(){
  const [replaying,setReplaying]=useState(false);
  return <div className="landing-page">
    <header className="landing-nav"><button className="landing-brand" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}><b>Trace<span>X</span></b><small>Financial Crime Intelligence</small></button><nav><a href="#how">How it works</a><a href="#intelligence">Intelligence</a><a href="#evidence">Evidence</a></nav><button className="landing-signin" onClick={()=>navigate('/investigate')}>Open workspace <span>→</span></button></header>
    <main>
      <section className="landing-hero">
        <div className="hero-intro"><span className="landing-eyebrow">Blockchain financial intelligence</span><div className="trace-label">TRACE <i>X</i><small>FINANCIAL CRIME INTELLIGENCE</small></div><h1>Follow the money.<br/><em>Reveal the network.</em></h1><p>TraceX helps cybercrime investigators trace cryptocurrency movement, uncover intermediary wallets, identify potential exchange and VASP endpoints, connect related investigations, and preserve evidence.</p><div className="landing-actions"><button className="landing-primary" onClick={()=>navigate('/investigate')}>Start investigation <span>→</span></button><a href="#how">Explore how it works <span>↓</span></a></div></div>
        <div className="hero-visual"><div className="trace-console"><header><div><span className="console-kicker"><i/> Evidence graph</span><b>CASE-1042 · Fund-flow reconstruction</b></div><div className="console-actions"><span>ETH MAINNET</span><span>2 HOPS</span><button aria-label="More graph controls">•••</button></div></header><div className="trace-canvas"><NetworkDiagram/><aside className="trace-inspector"><span className="inspector-label">Selected entity</span><b>Collector wallet</b><code>0x9D3...E71</code><dl><div><dt>Received</dt><dd>2.4 ETH</dd></div><div><dt>Risk signals</dt><dd className="risk-high">04</dd></div><div><dt>Observed outflow</dt><dd>3 transfers</dd></div></dl><small>Observed blockchain activity. Requires investigator review.</small></aside></div><footer><span><i className="legend-suspect"/> Reported wallet</span><span><i className="legend-intermediary"/> Intermediary</span><span><i className="legend-vasp"/> Potential VASP</span><b>8 entities · 9 transfers</b></footer></div></div>
      </section>
      <section className="live-strip"><div><i className="live-dot"/>LIVE NETWORK <b>SIMULATED</b></div><div className="metric-blue"><span>ACTIVE INVESTIGATIONS</span><strong>1,284</strong></div><div className="metric-violet"><span>WALLETS ANALYZED</span><strong>48,210</strong></div><div className="metric-amber"><span>TRANSACTIONS TRACED</span><strong>2.8M</strong></div></section>
      <section className="how-section" id="how"><div className="section-intro"><span className="landing-eyebrow">Investigation workflow</span><h2>Turn a reported wallet into<br/>an investigative lead.</h2><p>TraceX keeps the reasoning legible: observed blockchain records, risk signals, and evidence remain connected through every stage.</p></div><div className="flow-steps">{[['01','Report','Investigator receives a suspicious wallet address.'],['02','Trace','TraceX follows movement across connected wallets.'],['03','Connect','Identify exchanges, VASPs, patterns and related cases.'],['04','Act','Preserve evidence, alerts, recommendations and reports.']].map(([n,t,d])=><article key={n}><span>{n}</span><i/><h3>{t}</h3><p>{d}</p></article>)}</div></section>
      <section className="story-section"><div className="story-copy"><span className="landing-eyebrow">Investigation reconstruction · CASE-1042</span><h2>A path worth<br/><em>investigating.</em></h2><p>Funds received by a collector wallet were split through three intermediaries before reaching an observed exchange cluster.</p><div className="story-metrics"><b>2.4 <small>ETH</small></b><b>18 <small>MINUTES</small></b><b>5 <small>WALLETS</small></b><b>2 <small>HOPS</small></b><b>1 <small>POTENTIAL VASP</small></b></div><button className="landing-secondary" onClick={()=>{setReplaying(true);setTimeout(()=>setReplaying(false),3600)}}>{replaying?'Replaying fund flow…':'Replay investigation'} <span>▶</span></button></div><div className={replaying?'replaying':''}><NetworkDiagram story/></div></section>
      <section className="intelligence-section" id="intelligence"><div className="section-intro"><span className="landing-eyebrow">Cross-case intelligence</span><h2>One wallet can reveal<br/>an entire network.</h2><p>Relationships are investigative leads—not conclusions. TraceX explains what overlaps and leaves the final assessment to investigators.</p></div><div className="case-map"><svg viewBox="0 0 700 310"><path d="M105 90 L300 150 L495 75 M300 150 L520 240 M105 90 L205 252 M205 252 L520 240"/>{[['CASE-1042',105,90],['CASE-1088',495,75],['CASE-1137',205,252],['CASE-1191',520,240],['SHARED\nINTERMEDIARY',300,150]].map(([label,x,y])=><g key={label} transform={`translate(${x} ${y})`}><rect x="-65" y="-24" width="130" height="48" rx="3"/><text>{label.split('\n').map((v,i)=><tspan key={v} x="0" dy={i?11:0}>{v}</tspan>)}</text></g>)}</svg><div className="relationship-notes"><span>Shared infrastructure detected</span><span>Potential relationship</span><span>Requires investigator review</span></div></div></section>
      <section className="evidence-section" id="evidence"><div><span className="landing-eyebrow">Evidence chain</span><h2>Built for findings that<br/>can be reviewed.</h2><p>TraceX connects investigator observations to source records, so findings can be revisited, verified, and included in a defensible report.</p><button className="landing-secondary" onClick={()=>navigate('/investigate')}>Open TraceX workspace <span>→</span></button></div><div className="evidence-chain">{['Investigator finding','Supporting evidence','Blockchain transaction','Blockchain record'].map((x,i)=><React.Fragment key={x}><article><span>0{i+1}</span><b>{x}</b>{i===1&&<small>EV-0004 · Wallet attribution</small>}</article>{i<3&&<i>↓</i>}</React.Fragment>)}<div className="verified"><i>✓</i> Evidence integrity verified <small>SHA-256</small></div></div></section>
      <section className="closing"><span className="landing-eyebrow">TraceX workspace</span><h2>Start with one wallet.<br/><em>Understand the network.</em></h2><button className="landing-primary" onClick={()=>navigate('/investigate')}>Open TraceX workspace <span>→</span></button></section>
    </main><footer><div><b>Trace<span>X</span></b><small>Financial Crime Intelligence</small></div><nav><a onClick={()=>navigate('/investigate')}>Investigate</a><a onClick={()=>navigate('/cases')}>Cases</a><a onClick={()=>navigate('/network')}>Network</a><a onClick={()=>navigate('/monitoring')}>Monitoring</a><a onClick={()=>navigate('/alerts')}>Alerts</a><a onClick={()=>navigate('/copilot')}>Copilot</a><a onClick={()=>navigate('/reports')}>Reports</a></nav></footer>
  </div>;
}
