import React, { useMemo, useState } from 'react';
import Icon from '../components/Icon.jsx';
import { Badge, Button, CopyValue, EmptyState, ErrorState, MetricCard, Panel, SectionHeader } from '../components/Primitives.jsx';
import { CopilotPanel, EvidenceCenter } from '../components/IntelligencePanels.jsx';
import { caseLabel, formatDate, riskTone, shortAddress } from '../utils.js';

export function PageHeader({ eyebrow, title, description, action }) { return <header className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</header>; }

export function CasesPage({ cases, monitors, onOpenCase, onDelete }) {
  const [query,setQuery]=useState(''),[risk,setRisk]=useState('all'),[sort,setSort]=useState('newest');
  const visible=useMemo(()=>cases.filter(item=>(!query||[item.id,item.wallet_address].join(' ').toLowerCase().includes(query.toLowerCase()))&&(risk==='all'||item.risk_level===risk)).sort((a,b)=>sort==='risk'?(b.risk_score||0)-(a.risk_score||0):new Date(String(b.timestamp).replace(' UTC','Z'))-new Date(String(a.timestamp).replace(' UTC','Z'))),[cases,query,risk,sort]);
  return <div className="page-enter"><PageHeader eyebrow="Case intelligence" title="Investigation cases" description="Search and reopen stored evidence without rerunning blockchain analysis."/><Panel><div className="table-toolbar"><label className="table-search"><Icon name="search"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search case ID or wallet"/></label><select value={risk} onChange={event=>setRisk(event.target.value)}><option value="all">All risk levels</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select><select value={sort} onChange={event=>setSort(event.target.value)}><option value="newest">Newest cases</option><option value="risk">Highest risk</option></select><span className="result-count">{visible.length} cases</span></div>{visible.length?<div className="case-list">{visible.map(item=>{const monitor=monitors.find(value=>value.wallet_address?.toLowerCase()===item.wallet_address?.toLowerCase());return <article key={item.id}><span className={`case-risk-stripe risk-${riskTone(item.risk_level)}`}/><div className="case-list-id"><span>{caseLabel(item.id)}</span><CopyValue value={item.wallet_address}/></div><div className="case-list-date"><span>Created</span><strong>{formatDate(item.timestamp)}</strong></div><div className="case-list-stat"><span>Transactions</span><strong>{item.transaction_count||0}</strong></div><div className="case-list-stat"><span>Wallets</span><strong>{item.wallet_count||0}</strong></div><Badge tone={monitor?.status==='monitoring'?'success':'neutral'} dot>{monitor?.status==='monitoring'?'Monitored':'Inactive'}</Badge><Badge tone={riskTone(item.risk_level)}>{item.risk_level} · {item.risk_score}</Badge><div className="case-list-actions"><button onClick={()=>onOpenCase(item.id)}>Open <Icon name="arrow"/></button><button className="delete-button" onClick={()=>onDelete(item.id)} aria-label={`Delete ${caseLabel(item.id)}`}><Icon name="close"/></button></div></article>})}</div>:<EmptyState icon="cases" title="No stored cases match" description="Adjust the current search or begin a new wallet investigation."/>}</Panel></div>;
}

export function MonitoringPage({ monitors, cases, onOpenCase, onStop, onStart }) {
  const active=monitors.filter(item=>item.status==='monitoring');
  return <div className="page-enter"><PageHeader eyebrow="Continuous observation" title="Monitoring command center" description="Review wallet watches and their latest provider-observed activity." action={<Button icon="investigate" onClick={onStart}>New investigation</Button>}/><div className="metric-grid four"><MetricCard label="Tracked wallets" value={monitors.length} tone="blue"/><MetricCard label="Active watches" value={active.length} tone="teal"/><MetricCard label="Stopped watches" value={monitors.length-active.length} tone="amber"/><MetricCard label="Provider" value="Ethereum" detail="Configured blockchain service" tone="purple"/></div><Panel><SectionHeader eyebrow="Real monitoring state" title="Wallet watches" description="Polling creates alerts only for supported activity rules; no presentation-only alerts are generated."/>{monitors.length?<div className="monitor-grid">{monitors.map(item=>{const linked=cases.find(value=>value.id===item.investigation_id);return <article key={item.id||`${item.wallet_address}-${item.created_at}`}><header><span className={`monitor-pulse ${item.status==='monitoring'?'active':''}`}><i/></span><div><CopyValue value={item.wallet_address}/><small>{linked?caseLabel(linked.id):'No linked case'}</small></div><Badge tone={item.status==='monitoring'?'success':'neutral'}>{item.status}</Badge></header><dl><div><dt>Last checked</dt><dd>{formatDate(item.last_checked_at)}</dd></div><div><dt>Last activity</dt><dd>{formatDate(item.last_transaction_timestamp)}</dd></div><div><dt>Latest transaction</dt><dd>{item.last_transaction_hash?shortAddress(item.last_transaction_hash):'Not available'}</dd></div><div><dt>Trace policy</dt><dd>{item.max_hops||2} hops · {item.max_wallets||8} wallets</dd></div></dl><footer>{linked&&<Button variant="secondary" onClick={()=>onOpenCase(linked.id)}>Open investigation</Button>}{item.status==='monitoring'&&<Button variant="ghost" onClick={()=>onStop(item.wallet_address)}>Stop monitoring</Button>}</footer></article>})}</div>:<EmptyState icon="monitoring" title="No monitored wallets" description="Start monitoring from a stored investigation to watch for new supported activity." action={<Button onClick={onStart}>Open investigation</Button>}/>}</Panel></div>;
}

export function AlertsPage({ alerts, onUpdate, onOpenCase }) {
  const counts={NEW:alerts.filter(item=>item.status==='NEW').length,ACKNOWLEDGED:alerts.filter(item=>item.status==='ACKNOWLEDGED').length,RESOLVED:alerts.filter(item=>item.status==='RESOLVED').length};
  return <div className="page-enter"><PageHeader eyebrow="Evidence-triggered events" title="Intelligent alert center" description="Alerts are generated only from real monitoring observations and deterministic rules."/><div className="metric-grid three"><MetricCard label="New alerts" value={counts.NEW} tone="red"/><MetricCard label="Acknowledged" value={counts.ACKNOWLEDGED} tone="amber"/><MetricCard label="Resolved" value={counts.RESOLVED} tone="teal"/></div><Panel>{alerts.length?<div className="alert-feed">{alerts.map(item=><article key={item.id}><span className={`alert-severity alert-${String(item.severity||'INFO').toLowerCase()}`}>{item.severity||'INFO'}</span><div className="alert-copy"><header><strong>{item.title}</strong><Badge tone={item.status==='NEW'?'danger':item.status==='RESOLVED'?'success':'warning'}>{item.status}</Badge></header><p>{item.description}</p><div><CopyValue value={item.wallet_address}/><span>{formatDate(item.timestamp||item.created_at)}</span>{item.transaction_hash&&<CopyValue value={item.transaction_hash}/>}</div></div><div className="alert-actions">{item.investigation_id&&<button onClick={()=>onOpenCase(item.investigation_id)}>Open case</button>}{item.status==='NEW'&&<button onClick={()=>onUpdate(item.id,'acknowledge')}>Acknowledge</button>}{item.status!=='RESOLVED'&&<button onClick={()=>onUpdate(item.id,'resolve')}>Resolve</button>}</div></article>)}</div>:<EmptyState icon="alerts" title="No monitoring alerts" description="No supported alert rule has produced evidence. This is not a claim that monitored wallets are safe."/>}</Panel></div>;
}

export function ReportsPage({ cases, current, network, onOpenCase, onToast }) {
  return <div className="page-enter"><PageHeader eyebrow="Investigation outputs" title="Reports & evidence center" description="Generate attributable evidence packages from stored cases."/>{current?<><section className="selected-report-case"><div><Badge tone={riskTone(current.risk?.level)}>{current.risk?.level} · {current.risk?.score}</Badge><div><span>Selected case</span><h2>{caseLabel(current.investigation_id)}</h2><CopyValue value={current.start_wallet}/></div></div><Button variant="secondary" onClick={()=>onOpenCase(current.investigation_id)}>Open workspace</Button></section><EvidenceCenter investigation={current} network={network} onToast={onToast}/></>:<Panel><EmptyState icon="reports" title="Select a stored case" description="Open an investigation to generate PDF, CSV, and JSON evidence outputs." action={cases[0]&&<Button onClick={()=>onOpenCase(cases[0].id)}>Open latest case</Button>}/></Panel>}</div>;
}

export function SystemPage({ config }) {
  const sources=[['Alchemy','Primary blockchain provider',config?.providers?.alchemy],['Etherscan','Fallback blockchain provider',config?.providers?.etherscan],['Chainabuse','External threat intelligence',config?.externalIntelligence?.chainabuse],['Groq','Investigation Copilot',config?.copilot?.configured],['Fraud Network','Deterministic cross-case engine',config?.fraudNetwork?.configured],['Bridge Registry',`${config?.bridgeIntelligence?.verifiedContracts||0} provenance-backed Ethereum contract(s)`,config?.bridgeIntelligence?.configured],['Cross-chain',config?.crossChain?.reason,config?.crossChain?.correlation_verified]];
  const status=value=>typeof value==='string'?value:(value?'CONFIGURED':'UNAVAILABLE');
  return <div className="page-enter"><PageHeader eyebrow="Platform configuration" title="Data source health" description="Configuration readiness from the backend. No API keys or secrets are exposed."/><Panel><div className="source-grid">{sources.map(([name,role,ready])=>{const value=status(ready), available=['CONFIGURED','AVAILABLE','FALLBACK ACTIVE'].includes(value);return <article key={name}><span className={`source-logo source-${name.toLowerCase().replace(' ','-')}`}>{name.slice(0,2).toUpperCase()}</span><div><h3>{name}</h3><p>{role}</p></div><Badge tone={available?'success':'warning'} dot>{value}</Badge></article>;})}</div><div className="system-note"><Icon name="system"/><div><strong>Health status semantics</strong><p>Configured means the backend has the required credential or internal service. It does not perform recurring quota-consuming health calls. Provider failures degrade through explicit error and fallback states.</p></div></div></Panel></div>;
}

export function NetworkLanding({ cases, onOpenCase }) { return <div className="page-enter"><PageHeader eyebrow="Cross-case intelligence" title="Fraud network intelligence" description="Open a stored case to investigate shared wallets, intermediaries, destinations, paths, and VASPs."/><Panel>{cases.length?<div className="network-case-picker">{cases.map(item=><button key={item.id} onClick={()=>onOpenCase(item.id,'network')}><span className={`risk-line risk-${riskTone(item.risk_level)}`}/><div><strong>{caseLabel(item.id)}</strong><CopyValue value={item.wallet_address}/></div><span>{item.transaction_count} transactions · {item.wallet_count} wallets</span><Icon name="network"/></button>)}</div>:<EmptyState icon="network" title="No cases available for correlation" description="Complete at least one investigation to build the cross-case wallet index."/>}</Panel></div>; }

export function StandaloneCopilot({ current, onOpenCase, cases }) { return <div className="page-enter"><PageHeader eyebrow="Grounded investigation assistant" title="TraceX Investigation Copilot" description="Ask questions against the active stored case and deterministic TraceX evidence." action={!current&&cases[0]?<Button onClick={()=>onOpenCase(cases[0].id,'copilot')}>Load latest case</Button>:null}/><CopilotPanel investigation={current} standalone/></div>; }
